### ISSUE TITLE
v0.1.1 milestone

### ISSUE THREAD

**Issue by Hatsushigure** [Hatsushigure/DynamicSpot#15]
## 新增内容
- [x] 加入日志系统
- [x] 加入调试菜单
  - [x] 调试自动颜色
## 漏洞修复
- [x] 修复 [#14 颜色显示不清楚](https://github.com/Hatsushigure/DynamicSpot/issues/14)
- [x] 修复 [#17 倒计时不会自动更新](https://github.com/Hatsushigure/DynamicSpot/issues/17) 
- [x] 修复 [#22 日期计算有问题](https://github.com/Hatsushigure/DynamicSpot/issues/22)
- [x] 修复 [#24 异常获取焦点](https://github.com/Hatsushigure/DynamicSpot/issues/22)
## 常规更改
- [x] [#18 动画微调](https://github.com/hatsushigure/dynamicspot/issues/18)
## 其他
- [x] 合并开发分支
- [x] 打包
