### ISSUE TITLE
milestone v0.1.2

### ISSUE THREAD

**Issue by Hatsushigure** [Hatsushigure/DynamicSpot#29]
## 新增功能
- [x] [#30 调试菜单加入控制显示状态选项](https://github.com/Hatsushigure/DynamicSpot/issues/30)
## 漏洞修复
- [x] 修复 [#20 播放动画有时会有白边](https://github.com/Hatsushigure/DynamicSpot/issues/20)
- [ ] ~修复 [#33 文本颜色闪烁](https://github.com/Hatsushigure/DynamicSpot/issues/33)~
## 常规更改
- [x] 再次调整动画
- [x] 调整日志输出, 自动检测颜色时不再输出日志
## 其他任务
- [x] 修改版本号
- [x] 合并开发分支
- [x] 打包并发布
